# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - none

variables:
  IISWebsiteName: 'AzureTestProject'

resources:
  pipelines:
    - pipeline: 'buildpipeline'
      project: 'AzureTestProject'
      source: 'Build pipeline'
      branch: 'main'

stages:
  - stage: Deploy_website
    displayName: 'Deploy website'
    pool:
      vmImage: windows-latest
    jobs:
    - deployment: DeployWebsite
      displayName: 'Deploy website'
      environment: 'Windows server 2022'
      strategy:
        runOnce:
          deploy:
            steps:
            - checkout: none
            - download: 'buildPipeline'
              name: 'Download_Build_Artifacts'
              artifact: 'AzureTestProject'

            - task: IISWebAppDeploymentOnMachineGroup@0
              name: 'DeployIIS'
              displayName: 'Deploy IIS'
              inputs:
                WebSiteName: '${{ variables.IISWebsiteName }}'
                Package: '$(Pipeline.Workspace)\buildPipeline\AzureTestProject\RoundTheCode.AzureTestProject'
                TakeAppOfflineFlag: true
            - task: IISWebAppManagementOnMachineGroup@0
              name: 'StartIIS'
              displayName: 'Start IIS'
              inputs:
                IISDeploymentType: 'IISWebsite'
                ActionIISWebsite: 'StartWebsite'
                StartStopWebsiteName: '${{ variables.IISWebsiteName }}'